spring.application.name=catequiza

## Banco para testes
spring.datasource.url=jdbc:postgresql://localhost:5432/catequiza-test
spring.datasource.username=catequiza
spring.datasource.password=catequiza
spring.jpa.hibernate.ddl-auto=update